src/engineio/packet.rs
src/engineio/socket.rs
src/engineio/transport.rs
src/lib.rs
src/socketio/event.rs
src/socketio/packet.rs
src/socketio/transport.rs

mixture of line justifications for readability and a couple spelling adjustments
thanks!

formatting etc - oliver

---

README.md

The idea behind this PR is, that we will change the code examples in the README.md file on a separate branch as it might be confusing to see an example with an unreleased version of the crate on the front page. This will get merged as soon as a new version is ready. Till then all updates effecting the example code in the README file will get tracked here.

WIP: Refactored README as ack usage changed

---

src/engineio/packet.rs
src/engineio/socket.rs
src/engineio/transport.rs
src/error.rs
src/lib.rs
src/socketio/packet.rs
src/socketio/transport.rs

Rather small refactoring change. Closes #21.

Implemented Error for error

---

.github/workflows/main.yml
Makefile
src/engineio/packet.rs
src/engineio/socket.rs
src/engineio/transport.rs
src/socketio/transport.rs

decode,encode parameters from vecu8 to bytes crate

Implementation of Issue #1 

---

README.md
src/lib.rs
src/socketio/transport.rs

This PR restructures the way the callback functions work. Until now the callback just received the Payload send by the server (`callback: FnMut(Payload) + ...`). This was an issue as soon as someone wanted to react to the payload and answer the server immediately. The new callback type (`callback: FnMut(Payload, Socket) + ...`) allows such behavior. The transport layer makes sure that a valid `Socket` is passed into the function. This should get merged after PR #25 as it builds upon the changes.

Restructure callbacks

---

ci/README.md

Added a README which explains testing/the ci pipeline of this repo

Added a CI README file

---

Cargo.toml
src/engineio/socket.rs
src/engineio/transport.rs
src/socketio/transport.rs

This corrects the memory ordering used with `AtomicBool` types.

Correct memory ordering

---

README.md
Roadmap.md

Just moving recent changes to refactoring

Update to main

---

src/engineio/packet.rs
src/engineio/socket.rs
src/error.rs
src/socketio/transport.rs

This will be used in socket later.

0.3.0 handshake packet

---

ci/engine-io-secure.js
ci/engine-io.js

Send messages back to the client

---

.devcontainer/devcontainer.json

In light of https://github.com/1c3t3a/rust-socketio/pull/59

Code spell checker

---

src/engineio/packet.rs
src/engineio/socket.rs
src/error.rs

Use From and Into rather than encode/decode

Into rather than encode

---

.devcontainer/Dockerfile
.devcontainer/docker-compose.yaml

This allows for running tarpaulin in the devcontainer

feat: unconfined devcontainer

---

CONTRIBUTING.md

Run basic tests before commits, enforce conventional commits

docs: add git hooks

---

.devcontainer/docker-compose.yaml

Inspired by https://github.com/1c3t3a/rust-socketio/issues/67#issuecomment-892971548 .

Add debug to node servers

---

README.md
src/error.rs
src/lib.rs
src/socketio/socket.rs

Inspired by:
- https://github.com/socketio/socket.io/blob/310f8557a794bb94291cf8d5ef5f31d8258a3338/lib/index.ts#L622
- https://rust-lang.github.io/api-guidelines/type-safety.html#builders-enable-construction-of-complex-values-c-builder

0.3.0 socketio socket refactor

---

src/engineio/socket.rs
src/engineio/transport.rs
src/engineio/transports/mod.rs
src/engineio/transports/websocket.rs
src/engineio/transports/websocket_secure.rs

Trait objects are a royal pain to deal with.

feat: TransportTypes

---

src/engineio/client/mod.rs
src/engineio/client/socket.rs
src/engineio/mod.rs
src/engineio/packet.rs
src/engineio/socket.rs
src/engineio/transport.rs
src/lib.rs
src/socketio/client/mod.rs
src/socketio/client/socket.rs
src/socketio/mod.rs
src/socketio/transport.rs

Relies on:
- https://github.com/1c3t3a/rust-socketio/pull/79
- https://github.com/1c3t3a/rust-socketio/pull/78
Moved socket in preparation for #91 , without this PR the diff would be impossible to read.

0.3.0 socketio move socket

---

socketio/src/client/socket.rs

Depends on:
- https://github.com/1c3t3a/rust-socketio/pull/98
Socketio half of #94

0.3.0 socketio specify transport types

---

engineio/src/client/socket.rs
engineio/src/lib.rs
engineio/src/socket.rs
engineio/src/transport.rs
socketio/src/client/builder.rs
socketio/src/client/socket.rs
socketio/src/error.rs

Breaking change: Removed IllegalActionAfterOpen

refactor!: assigned versions to todos

---

Cargo.lock
engineio/Cargo.toml
engineio/src/asynchronous/async_transports/websocket.rs
engineio/src/asynchronous/async_transports/websocket_secure.rs

This supersedes #159 and #161.

Bump tokio-tungstenite version

---

.devcontainer/docker-compose.yaml
.github/workflows/coverage.yml
.github/workflows/test.yml
ci/socket-io-auth.js
ci/start_test_server.sh
socketio/src/client/builder.rs
socketio/src/client/client.rs
socketio/src/lib.rs

Add option to send data in socketio opening request, to authenticate with the server.
https://socket.io/docs/v4/client-options/#auth

Implement socketio auth

---

ci/README.md

Hi, while trying to set up the project locally, I ran into some issues. After finding out what to do, I figured why not update the readme. Hope this helps.

docs: clarify instructions on how to run tests locally

---

.devcontainer/devcontainer.json

https://blog.rust-lang.org/2022/02/21/rust-analyzer-joins-rust-org.html

ci(devcontainer): rust-analyzer changed ownership

---

socketio/src/asynchronous/client/client.rs

not use unwrap maybe more friendly to new reader

chore: use match instead of unwrap

---

engineio/src/transports/polling.rs

`poll` and `emit` will wait for each other if use `Mutex`

fix: polling client no need lock

---

socketio/src/socket.rs

fix: emit plain text

---

socketio/src/client/client.rs

fix: on close callback when server down without close packet

---

socketio/src/client/builder.rs

docs: added code block closing

---

socketio/src/asynchronous/client/builder.rs
socketio/src/asynchronous/client/client.rs

This change allows for awaiting futures in asynchronous callbacks.
Sadly, I did not manage to keep the `Stream` implementation of the client as this would mean storing the `Unfold` somewhere in the client.
Let me know if you see potential issues with this method. :)
Closes #313

fix: allow awaiting async callbacks

---

engineio/src/header.rs

- Represent `HeaderName` by `Box<str>` instead of `String` to reduce its size.
- Replace `HeaderName: ToString` with `HeaderName: Display` which comes with a free `ToString` impl
- Avoid an allocation when creating `HttpHeaderName `
- Create `HttpHeaderMap` via `Iterator::collect` instead of repeated `HttpHeaderMap::append`

perf(engineio): optimize headers
