Cargo.toml
Makefile
README.md
example/engine-io.js
example/example_engineio.rs
example/socket-io.js
src/engineio/packet.rs
src/engineio/socket.rs
src/engineio/transport.rs
src/error.rs
src/lib.rs
src/socketio/event.rs
src/socketio/packet.rs
src/socketio/transport.rs

During development I've often came across problems related to async rust. When I started the project I thought it would be a nice thing to have the whole crate use rusts async API, but now it just feels like it decreases the development speed. As this is mostly a learning project for me, I think it might be a good idea to refactor the code to be normal, sync rust. We might switch back to async later, when the whole protocol is implemented and the API is fix.
Changes in this PR:
- Removed all async code (originated from the async HTTP requests made via reqwest).
- Changed the callback functions of the socket.io client from `Fn` to `FnMut`, because this allows using the socket within the callback.

Removed all async code

---

Cargo.toml
src/lib.rs
src/socketio/packet.rs
src/socketio/transport.rs

This PR refactors the way the `socket.io` packet decoder parses the packet. Till now this was done via parsing the packet from a string, which involved parsing an utf-8 string. This PR changes this by parsing the packet from pure bytes.

Refactored packet decoding

---

.github/workflows/coverage.yml
codecov.yml
src/lib.rs
src/socketio/transport.rs

The current implementation missed a disconnection ability for the `socket.io` socket, as mentioned in #43.

Added a disconnect method for the socket.io socket

---

.github/workflows/coverage.yml

Hopefully fixes the `Please provide an upload token from codecov.io with valid arguments` error.

ci: Bump codecov action version

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yaml
docker-compose.yaml
src/engineio/socket.rs
src/engineio/transport.rs
src/lib.rs
src/socketio/transport.rs

Adds a [devcontainer](https://code.visualstudio.com/docs/remote/containers) (VSCode specific). It allows for developers to have a reproducible environment to compile and test. This does not effect existing developers and is purely voluntary.
As the project grows, such as having a [server implementation](https://github.com/1c3t3a/rust-socketio/issues/32) (Which I plan on doing shortly), having all the servers/clients needed for testing available during development speeds up testing.
Also modified the tests to optionally read from an environment variable.

feat: devcontainer

---

Cargo.toml
src/engineio/packet.rs
src/engineio/socket.rs
src/error.rs
src/socketio/packet.rs
src/socketio/transport.rs

Renamed error types to conform to https://rust-lang.github.io/api-guidelines/naming.html#names-use-a-consistent-word-order-c-word-order

0.3.0 refactor errors

---

.github/workflows/build.yml
.github/workflows/coverage.yml
.github/workflows/test.yml

Cache build dependencies to cut down on CI time. Presently takes ~5min to run tests. Should this target refactoring or master?
References:
- https://dev.to/github/caching-dependencies-to-speed-up-workflows-in-github-actions-3efl
- https://github.com/actions/cache/blob/main/examples.md#rust---cargo
- Cherry picked from https://github.com/1c3t3a/rust-socketio/pull/69

Main cache cargo

---

.github/workflows/build.yml
.github/workflows/coverage.yml
.github/workflows/test.yml

Cache build dependencies to cut down on CI time. Presently takes ~5min to run tests. Should this target refactoring or master?
References:
- https://dev.to/github/caching-dependencies-to-speed-up-workflows-in-github-actions-3efl
- https://github.com/actions/cache/blob/main/examples.md#rust---cargo

0.3.0 cache cargo

---

src/engineio/transports/websocket.rs
src/socketio/transport.rs

The sleep was for debug purposes it should not be in repo.

feat: remove sleep from websocket

---

src/lib.rs
src/socketio/socket.rs
src/socketio/transport.rs

> That's nice! I always stumbled across the `Result` returned by the `set_namespace` method, that one's definitely better!
- https://github.com/1c3t3a/rust-socketio/pull/77#pullrequestreview-729576506
Good catch the type doesn't need to be result anymore.

feat!: namespace return self

---

.devcontainer/devcontainer.json

Switched to rust-analyzer per recommendation [here](https://github.com/1c3t3a/rust-socketio/pull/50#discussion_r669493106). Looks like autocomplete is working now (perhaps I didn't wait long enough before? rust-anaylzer's start up time is significantly greater than rls). Also found (and mentioned in a comment) the settings in rust-analyzer to make it less noisy.

Devcontainer rust analyzer

---

engineio/src/callback.rs
engineio/src/client/socket.rs
engineio/src/error.rs
engineio/src/lib.rs
engineio/src/packet.rs
engineio/src/socket.rs
socketio/src/client/socket.rs
socketio/src/socket.rs

Refactor to make IllegalActionAfterOpen impossible in engineio. This is not a breaking change thanks to @1c3t3a having the wisdom not to make public yet. Thank you.

refactor: move callback init to builder

---

engineio/src/client/socket.rs
engineio/src/packet.rs
engineio/src/socket.rs
socketio/src/client/builder.rs
socketio/src/client/callback.rs
socketio/src/client/mod.rs
socketio/src/client/socket.rs
socketio/src/event.rs
socketio/src/lib.rs
socketio/src/socket.rs

Sorry about the mega PR, things got out of hand. Did manage to make the code 200 lines shorter.
This PR cleans up 
- https://github.com/1c3t3a/rust-socketio/pull/101#discussion_r698482795
- https://github.com/1c3t3a/rust-socketio/pull/101#discussion_r698477692
Other notes:
- Iterator should be usable by users now (so long as they connect_manual)
- Implementing trait based callbacks should be relatively easy (see callback function)
- Will require some refactoring internally to get server implementation to share code (see hard coded engineio socket client in common socketio socket)
Breaking changes:
- Event type on callback no longer needs into

! 0.3.0 socketio callback refactor

---

engineio/Cargo.toml

This is a small change that makes sure to only compile the necessary bits of the websocket crate.

Optimize websocket import to not compile tokio

---

ci/socket-io.js
socketio/src/client/socket.rs

Problem was two-fold:
- no socket.of("/admin").on("connection", callback) in ci
- Integration tests didn't use namespaces other than /

0.3.0 invalid namespace

---

engineio/src/header.rs

Relies on:
- https://github.com/1c3t3a/rust-socketio/pull/119

0.3.0 engineio websocket header cannot fail

---

src/error.rs
src/lib.rs
src/socketio/packet.rs
src/socketio/transport.rs

This will be the final update to 0.2.X before 0.3.0 goes live. Uses deprecation notes to walk the user through how to upgrade from 0.2.X to 0.3.0. AKA if the users resolve all deprecation warnings described in the notes they can upgrade to 0.3.0 without errors. (even without looking at the changelog)

0.2.X deprecation

---

README.md
engineio/benches/engineio.rs
engineio/src/client/client.rs
engineio/src/client/mod.rs
engineio/src/lib.rs
socketio/examples/callback.rs
socketio/examples/readme.rs
socketio/examples/secure.rs
socketio/src/client/builder.rs
socketio/src/client/callback.rs
socketio/src/client/client.rs
socketio/src/client/mod.rs
socketio/src/lib.rs
socketio/src/socket.rs

Breaking changes:
- renamed socket to client. Left a compatibility shim for now if they were using the import in the crate root.

refactor!: rename socket to client

---

engineio/src/transports/websocket_secure.rs

This PR closes #133 by adding a timeout on the Websocket's receive method. This way the lock on the client isn't held until the next message is received.

Add timeout on secure websocket `receive` method

---

Cargo.lock
engineio/Cargo.toml
engineio/src/asynchronous/async_socket.rs
engineio/src/asynchronous/async_transports/polling.rs
engineio/src/asynchronous/async_transports/websocket.rs
engineio/src/asynchronous/async_transports/websocket_general.rs
engineio/src/asynchronous/async_transports/websocket_secure.rs
engineio/src/asynchronous/client/async_client.rs
engineio/src/asynchronous/client/builder.rs
engineio/src/asynchronous/transport.rs
engineio/src/transports/websocket.rs
engineio/src/transports/websocket_secure.rs
socketio/src/client/builder.rs

This is an alternative implementation to #154, that does not implement stream for every type but rather provides a method `stream` on every type that returns a stream.
The stream is mapped on every layer (from acquiring the bytes to parsing packets).
~~The issue with this implementation is the return type of the `Client`s stream method, as this returns a stream of futures which is verbose to handle~~ nvm, I found the `then` method that allows an async context.
I also sticked to reqwest, as tls handling in hyper is quite complicated and reqwest delivers a clean API for configuring a client.

Implement Stream for all engine.io async types and remove poll methods, version 2

---

ci/package.json

This is done due to a security alert, for more information visit: https://github.com/advisories/GHSA-273r-mgr4-v34f

ci: bump engine.io-js dependency version

---

ci/socket-io-auth.js
socketio/src/client/builder.rs
socketio/src/client/callback.rs
socketio/src/client/client.rs

Add option to listen on any recived event
https://socket.io/docs/v4/client-api/#socketonanycallback
Update socket_io_auth_builder_integration (recive "auth" event instead of emitting with ack)

Implement socketio onAny

---

Cargo.lock
engineio/Cargo.toml
engineio/src/asynchronous/async_socket.rs
engineio/src/asynchronous/async_transports/polling.rs
engineio/src/asynchronous/async_transports/websocket.rs
engineio/src/asynchronous/async_transports/websocket_general.rs
engineio/src/asynchronous/async_transports/websocket_secure.rs
engineio/src/asynchronous/client/async_client.rs
engineio/src/asynchronous/client/builder.rs
engineio/src/asynchronous/generator.rs
engineio/src/asynchronous/mod.rs
engineio/src/asynchronous/transport.rs
engineio/src/transports/websocket.rs
engineio/src/transports/websocket_secure.rs
socketio/src/client/client.rs

This PR changes the `stream` implementation and usage in the engine.io trait. Earlier PRs introduced async Streams in engine.io but the ergonomics were quite difficult and the implementation was hard to understand. This is changed in this PR, with the introduction of [`async_stream`](https://docs.rs/async-stream/0.3.3/async_stream/index.html), a crate that exposes a handy `try_stream!` macro for writing async generators that implement `futures_util::Stream`.
The changes made here leave some open questions on how sound the generator implementation actually is. Especially for the long polling case, the following issue arises: 
https://github.com/1c3t3a/rust-socketio/blob/a643468d2bf5b7e6db870264ce62e1c6b526377f/engineio/src/asynchronous/async_transports/polling.rs#L96-L119
A solution would …

refactor: change `stream` implementation in engine.io

---

socketio/src/client/builder.rs

`Into<serde_json::Value>` always converts string to `serde_json::Value::String("...")`.
The following test fails, because One gets parsed as an Object, while the string gets converted into `serde_json::Value::String` 
```rs
#[test]
fn json_compare_test() {
let using_macro = serde_json::json!({
"hello": "world"
});
let using_into: serde_json::Value = "{ \"hello\": \"world\" }".into();
assert_eq!(using_into, using_macro)
}
```
[`serde_json::from_str`](https://docs.serde.rs/serde_json/fn.from_str.html) could be used, but that would mean the method would need to use `Into<String>` as a parameter, which I think would be annoying, as most common use case of this method is using json!() in the method's args.
```rs
let socket = ClientBuilder::new("http://localhost:4204/")
.namespace("/admin") …
```

fix!: incorrect json parsing in ClientBuilder.auth

---

socketio/src/error.rs
socketio/src/packet.rs
socketio/src/payload.rs

hi @1c3t3a,  the original decode logic treat payload as vec[u8] which is ok for unicode string, but not ok for utf8 which is `variable-width`.

fix: decode utf8

---

Cargo.lock
socketio/src/client/builder.rs
socketio/src/client/callback.rs
socketio/src/client/client.rs
socketio/src/client/raw_client.rs

implement support for `?Sync` callbacks

---

.github/workflows/coverage.yml
Cargo.lock
engineio/Cargo.toml
socketio/Cargo.toml

This changes the coverage action to move away from tarpaulin and instead use the new compiler-buildin llvm coverage tool.
This closes #45.

ci: Change coverage action to use llvm-cov

---

socketio/src/client/builder.rs
socketio/src/client/client.rs

I have a Socket.IO client that I want to automatically reconnect when disconnected by the server.
This adds an option to enable this.

Add reconnect_on_disconnect option to ClientBuilder

---

socketio/src/asynchronous/client/builder.rs
socketio/src/client/builder.rs

[current features](https://docs.rs/rust_socketio/latest/rust_socketio/#current-features) at the main page of the documentation lists the supported features correctly, but the [on method's documentation](https://docs.rs/rust_socketio/latest/rust_socketio/struct.SocketBuilder.html#method.on) seems to have a wrong event 'connect' instead of 'open'.
Code to verify:
```rust
let socket = SocketBuilder::new("http://localhost:3001")
.on("open", |_,_| println!("Connected!")) // This triggers, "connect" does not trigger
.connect()
.expect("Connection failed");
```
It took me a while to figure this out, I hope this helps someone else!

Fix wrong event 'connect' to 'open'

---

socketio/src/asynchronous/socket.rs

Similar to the synchronous client, this adds a check to the asynchronous client to only handle packets whose packet_id is either Message or MessageBinary. All other packets like heartbeats are ignored in the SocketIO client stream, as they are handled separately.
Closes #311

fix: only handle Message or MessageBinary packets in async client

---

engineio/src/packet.rs

Avoiding an intermediate `String` allocation when converting `Packet` into `Bytes`.

perf(engineio): optimize Bytes: From<Packet>

---

engineio/src/packet.rs

Replacing repeated `Vec::push` with a single `Iterator::collect` which is simpler, more idiomatic and more performant.
The [memchr](https://github.com/BurntSushi/memchr) crate can be used to speed this up further but it's outside the scope of this PR.

perf(engineio): optimize Payload: TryFrom<Bytes>

---

socketio/src/packet.rs

Avoiding intermediate allocations by always writing into the same `String` buffer.

perf(socketio): avoid allocs in Bytes: From<&Packet>

---

Cargo.lock
socketio/Cargo.toml
socketio/src/asynchronous/socket.rs
socketio/src/packet.rs
socketio/src/socket.rs

Ensuring a valid json format via [`serde::de::IgnoredAny`](https://docs.rs/serde/latest/serde/de/struct.IgnoredAny.html) instead of [`serde_json::Value`](https://docs.rs/serde_json/latest/serde_json/enum.Value.html) performs about 2x faster.
I added `serde` as direct dependency but since it was already used transitively, it's not a new dependency.
Closes #329 
I noticed a small discrepancy between [async](https://github.com/1c3t3a/rust-socketio/blob/b61c0376d08f53577ffdc58a1d355fdff60e68c1/socketio/src/asynchronous/socket.rs#L118-L120) and [non-async](https://github.com/1c3t3a/rust-socketio/blob/b61c0376d08f53577ffdc58a1d355fdff60e68c1/socketio/src/socket.rs#L107-L111) code; I can't judge which one is correct though.

perf(socketio): validate json via IgnoredAny

---

socketio/src/asynchronous/client/client.rs
socketio/src/asynchronous/socket.rs
socketio/src/client/raw_client.rs
socketio/src/event.rs
socketio/src/socket.rs

This avoids some more allocations by
- formatting events directly instead of using `String: From<Event>`
- creating events directly instead of using `Event: From<&str>`
I also copied the `handle_event` method of the async client for the non-async client.

perf(socketio): avoid allocs when dealing with events

---

socketio/src/asynchronous/client/builder.rs

When the packet stream closes, e.g. because the server terminated the connection, the stream returns None. Then, the next() function shouldn't be called again on the stream, as it is already closed.
Previously, we wouldn't handle this, which lead to a panic.
Before the fix which implemented the as_stream() function for the socket, the program wouldn't panic, but instead run in an endless loop which isn't ideal either.
Now, the loop which fetches the packets from the stream properly terminates. However, the program which uses the socket.io client currently isn't notified of the unexpected closure.
Closes #323 
While I tried writing a test for this, it appears that you can't assert whether some tokio thread panicked or not without having the handle to that thread (there is a feature in …

fix(async): handle close of packet stream to avoid panic

---

Cargo.lock
engineio/Cargo.toml
engineio/src/asynchronous/async_transports/websocket_secure.rs

This PR bumps the `tungstenite` (and `tokio-tungstenite` ) version to `0.20.1` to resolve a vulnerability.

Bump tungstenite version to `v0.20.1`

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yaml
ci/socket-io.js
socketio/examples/async.rs
socketio/examples/callback.rs
socketio/examples/readme.rs
socketio/src/asynchronous/client/builder.rs
socketio/src/asynchronous/client/client.rs
socketio/src/asynchronous/socket.rs
socketio/src/client/builder.rs
socketio/src/client/client.rs
socketio/src/client/raw_client.rs
socketio/src/lib.rs
socketio/src/packet.rs
socketio/src/payload.rs
socketio/src/socket.rs

Added new payload variant called `Text` to support multiple arguments encoded in JSON. The old Payload::String is deprecated, and will be removed shortly. Use `Payload::from(String)` to mimic old behavior
Built on top of @SalahaldinBilal 's work https://github.com/1c3t3a/rust-socketio/pull/379
Also fixed running doc tests in the devcontainer

feat!: support multiple arguments to the payload

---

Cargo.lock
socketio/Cargo.toml
socketio/src/asynchronous/client/builder.rs
socketio/src/asynchronous/client/client.rs
socketio/src/client/client.rs

The async client and builder can now attempt to reconnect to the server on connection errors.
Fixes #291

Async reconnections

---

socketio/src/asynchronous/client/builder.rs
socketio/src/asynchronous/client/callback.rs
socketio/src/asynchronous/client/client.rs
socketio/src/asynchronous/mod.rs

Async clients that are using the reconnect feature can now provide an optional callback that will be invoked before the server is reconnected. You may optionally update the address or auth settings in this callback and they will be applied when the client reconnects.
This is useful for updating auth tokens which may have expired by the time a reconnection is required.
Fixes #401

Add `on_reconnect` callback on the async client

---

engineio/src/asynchronous/async_socket.rs
engineio/src/asynchronous/client/async_client.rs
engineio/src/client/client.rs
engineio/src/error.rs
engineio/src/socket.rs
engineio/src/transport.rs
engineio/src/transports/polling.rs
engineio/src/transports/websocket.rs
engineio/src/transports/websocket_secure.rs

The Engine.IO protocol features a heartbeat mechanism which ensures that the connection between server and client is alive. During that heartbeat, the server sends PINGs to which the client responds with PONGs. Both parties can therefore detect whether the connection is still alive, based on the pingInterval and pingTimeout received in the initial handshake.
However, we previously didn't make use of that in the Engine.IO implementation, which lead to disconnects not being properly recognized.
We now respect these settings and return an error and disconnect the connection, once the pingInterval+pingTimeout time has passed.
See also https://socket.io/docs/v4/how-it-works/#disconnection-detection
Closes #358

fix(engineio): respect pingTimeout and pingInterval to stop connection

---

Cargo.lock
ci/socket-io.js
engineio/src/packet.rs
socketio/src/asynchronous/client/client.rs
socketio/src/client/raw_client.rs

tested on true workflow
a part of #385
and will fix #409

Fix the implementation for the multi payload

---

Cargo.lock
engineio/Cargo.toml

deps: Bump http, tungstenite and reqwest to depend on http.v1

---

socketio/src/client/raw_client.rs

Hi @1c3t3a, I came across an issue while trying to call `emit_with_ack` recursively like so:
```rust
socket
.emit_with_ack(
"event_with_ack",
json!({"event_with_ack": "first call"}),
Duration::from_secs(20000),
move |data, s| {
println!("Ack 1 received: {:#?}", data);
// This works
s.emit("event", json!({"event": "second call"}))
.expect("Server unreachable");
// This doesn't work due to deadlock on "outstanding_acks" in emit_with_ack(). The callback is never executed.
s.emit_with_ack(
"event_with_ack",
json!({"event_with_ack": "second call"}),
Duration::from_secs(20000),
|data, _| {
println!("Ack 2 received: {:#?}", data);
},
)
.expect("Server unreachable");
},
)
.expect("Server unreachable");
```
I noticed that **the second callback is never executed**, and the program just waits …

fix: deadlock on recursive emit_with_ack calls

---

ci/socket-io.js
socketio/src/asynchronous/client/client.rs
socketio/src/client/raw_client.rs
socketio/src/event.rs
socketio/src/lib.rs

When the async client connects to the server, it spawns a new thread to handle the arriving messages asynchronously, which is immediately detached with no chance of awaiting its completion.
For long-running programs (e.g. a client program that never really disconnects from the server) this can be problematic, as unexpected stream completions would go unnoticed. This may happen if the underlying tungstenite websocket shuts down ('Received close frame: None') but there are no engineio/socketio close frames. Hence, since the stream terminates, the message handling task stops without a Close or Error event being fired.
Thus, we now fire an additional Event::Close when the stream terminates, to signal the (potentially unexpected) close to the user.
Closes #448 
Once we settle on a final …

feat(socketio): notify client of transport completion

---

ci/socket-io-restart.js
socketio/src/asynchronous/client/builder.rs
socketio/src/asynchronous/client/client.rs

Hi,
please take a look and let me know if there's a different approach this project would like to take.
Also note that I tried to match the Builder's `opening_header` function and that means it also copies `Into<String>` that imho should've been `Into<HeaderName>`.
Closes #462

Add headers to ReconnectSettings
